apiVersion: v1
kind: Pod
metadata:
  name: debian2
  labels:
    app: debian2
spec:
  containers:
  - name: debian2
    image: debian:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always